name: Build APK

# Trigger this action when pushing to the master branch
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java (necessary for Gradle)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Restore keystore from base64 secret
      - name: Decode keystore and store it
        run: |
          mkdir -p $HOME/.android
          echo "$KESTORE_BASE64" | base64 -d > $HOME/.android/release.keystore
          echo "KEYSTORE_FILE_PATH=$HOME/.android/release.keystore" >> $GITHUB_ENV
        env:
          KESTORE_BASE64: ${{ secrets.KEYSTORE_FILE }}

      # Debug
      - name: Debug GitHub Context
        run: |
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"

      # Step 4: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 5: Set up Gradle (optional, but useful for caching)
      - name: Set up Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # Step 6: Set up environment variables (pass secrets)
      - name: Set up Keystore secrets
        run: |
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      # Step 7: Build the APK (use Gradle to build)
      - name: Build APK
        run: ./gradlew assembleRelease

      # Step 8: Upload the APK as an artifact (optional)
      - name: Upload APK as a GitHub release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
